### PR TITLE
Removed all merge errors. Further code refactorings.

### PR DESCRIPTION
**Pull request by dahall**
From prior merges, there were a bunch of merge comments sprinkled around the code files. I also went through and upgraded the syntax so that it uses things like expression methods, null-coalescing, etc. from newer C# versions.

### CODE REVIEW

**Comment by contre** [comment]
What I’ve reviewed so far looks good. When I can spend a bit more time on this, likely Monday, I’ll do a more thorough review.

Can you also check out what is causing the conflicts?

**Comment by dahall** [comment]
It is weird. When I look at the comparison of each conflicting file, it appears to only have the changes I made. I wonder if part of the conflict resolution you did changed the time stamp or something.

**Comment by contre** [comment]
Maybe. Might need to do a rebase or something. I must admit I’m not expert at github or git so it is highly likely I broke something.

**Comment by contre** [comment]
Looks to be related to tabs vs spaces I think. I guess it is throwing off the merge algo.

**Comment by dahall** [comment]
Ah. I typically default to tabs. What is your preference?

**Comment by contre** [comment]
I usually go with what Visual Studio defaults to for the language. C# has had spaces for quite a while so I go with that.

To help with this issue, I'll go ahead and create an editorconfig at some point soon.

**Comment by contre** [comment]
Can you undo all the space->tabs changes you've done and then hopefully that will reduce the conflicts and allow for merging this changeset.

**Comment by dahall** [comment]
@contre Sure. How many spaces do use for an indent?

**Comment by contre** [comment]
4 spaces

**Comment by dahall** [comment]
@contre I converted all tabs to spaces. Did this help?

**Comment by contre** [comment]
This appears to be beyond my ability to resolve easily.

I'm not sure what the proper path should be.

**Comment by dahall** [comment]
I'll pull the project file modifications I made initially and then reset my branch to the current branch of your project. I'll then restart with just the project file modifications and resubmit a PR.

**Comment by dahall** [comment]
It appears that all these changes have been incorporated into .master. I just pulled this and compared to mine and they are identical. Whatever you did last seemed to do it. You have the latest.

**Comment by czdietrich** [comment]
Thank you for all the work and time migrating to .NET Core. 

Is there an expected release date, when we could expect updated NuGets to be released?

**Pull request closed without merging**
