### PR TITLE
Support added for .NET Core 3.0 and file reformatting

### PR DESCRIPTION
**Pull request by dahall**
* Updated version to 1.1.4
* Converted projects to new SDK format. Added support for multiple .NET versions and .NET Core 3.0. 
* Removed nuspec files and AssemblyInfo.cs project attributes and incorporated into project files.
* Removed redundant native interfaces from ShellExtensions and use those declared in Shell. This required rework of some of the other dependent files.
* Added code to address #20 PR from contre's repository.
* Applied new cleanup tools from VS2019 and CodeMaid to all source files resulting in reordered members, removal of regions, and refactoring to C# 7 capabilities.

### CODE REVIEW

**Comment by dahall** [comment]
From what I can see, the easiest path for resolving the conflicting files may be to accept the changes to all *.csproj files and reject them from those *.cs files in conflict. Those .cs files in the Sensors and ShellObjectWatcher folders were not touched by my PR other than reformatting. However, my edits to the .csproj files should be the ones used going forward as they follow the new SDK schema and allow for .NET Core.

**Comment by contre** [comment]
ooof, messed up that merge. Fixing it up now

**Comment by dahall** [comment]
@contre When you get the merge done, I think it would be brilliant to change the title of the project to indicate that this version of the API Code Pack supports all current .NET Framework and .NET Core versions. I think it really differentiates this fork. Before publishing next, we can even add `net48` and `netcoreapp3.1` to the semicolon separated list in the `<TargetFrameworks>` tag in each `.csproj` file to enable support for .NET 4.8 and .NET Core 3.1. The resulting line in each project file would be
```xml
<TargetFrameworks>net452;net462;net472;net48;netcoreapp3.0;netcoreapp3.1</TargetFrameworks>
```

**Comment by dahall** [comment]
I just submitted another PR with the suggested changes above and have confirmed it builds.

**Comment by contre** [comment]
And I just merged it. Great work and I appreciate all the help.

**Comment by dahall** [comment]
If you'll add me to the project, I'd like to also pull in some of the great work from some of the other forks. Then I don't have to pull you in to review and merge every PR.

**Comment by contre** [comment]
For the time being, I would like to be in the loop for these things. I’m still on the hook, at the moment, to get the nugget packages updated.

When I’m next able to get to a computer and not just be on my phone, I’ll look into adding you as a contributor. This will likely be Monday

**Pull request merged**
