### PR TITLE
Switch from MD-5 to FNV-1a for hashcode implementation

### PR DESCRIPTION
**Pull request by DanFTRX**
There is no need for a cryptographically secure hash algorithm for a GetHashCode function, and using one just creates potential for violating security policies as time passes. (Such as the FIPS policy of no MD-5 usage at all)

### CODE REVIEW

**Comment by DanFTRX** [comment]
Resolves #32

**Comment by DanFTRX** [comment]
Also it would be nice if/when this is merged to get a new nuget release with it.

**Review by contre — CHANGES_REQUESTED** [review]

**Comment by contre** [comment]
Sorry on not reviewing this sooner. I forgot to hit the submit review button.

**Review by contre — APPROVED** [review]

**Comment by johnthagen** [comment]
@contre Could this be released onto Nuget? We are currently unable to use this package due to the FIPS issue.

Thank you!

**Pull request merged**
